"""freshness, quality score, audit before-after and sequence

Revision ID: 6a01a4bbfe77
Revises: a1b2c3d4e5f6
Create Date: 2026-08-19 19:09:56.432704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a01a4bbfe77'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seq', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('before', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('after', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_audit_events_seq'), ['seq'], unique=False)

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quality_detail', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('quality_detail')
        batch_op.drop_column('quality_score')

    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_seq'))
        batch_op.drop_column('after')
        batch_op.drop_column('before')
        batch_op.drop_column('seq')

    # ### end Alembic commands ###
