"""initial schema

Revision ID: fe42a8d6f5a4
Revises: 
Create Date: 2026-08-19 17:41:49.525136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe42a8d6f5a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_firms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('frameworks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(), nullable=False),
    sa.Column('entry_hash', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('audit_firm_id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_firm_id'], ['audit_firms.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('artefact_type', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('extracted_attributes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('status_detail', sa.Text(), nullable=False),
    sa.Column('lifecycle_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_controls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('clause', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'framework', 'clause')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('audit_firm_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['audit_firm_id'], ['audit_firms.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_template_version', sa.String(), nullable=False),
    sa.Column('requested_attributes', sa.JSON(), nullable=False),
    sa.Column('validated_output', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_control_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_control_id'], ['org_controls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_control_id', 'user_id')
    )
    op.create_table('engagement_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'framework')
    )
    op.create_table('evidence_attributes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'name')
    )
    op.create_table('evidence_control_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('clause', sa.String(), nullable=False),
    sa.Column('ucos', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(), nullable=False),
    sa.Column('ai_prompt_version', sa.String(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('auditor_verdict', sa.String(), nullable=True),
    sa.Column('locked_by_engagement_id', sa.String(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('unlock_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['locked_by_engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'framework', 'clause')
    )
    op.create_table('gaps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('link_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('required_action', sa.Text(), nullable=False),
    sa.Column('actual_value', sa.String(), nullable=True),
    sa.Column('required_value', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_evidence_id', sa.String(), nullable=True),
    sa.Column('resolution_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['evidence_control_links.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('gap_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gap_id'], ['gaps.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('gaps')
    op.drop_table('evidence_control_links')
    op.drop_table('evidence_attributes')
    op.drop_table('engagement_allocations')
    op.drop_table('control_assignments')
    op.drop_table('ai_runs')
    op.drop_table('users')
    op.drop_table('org_controls')
    op.drop_table('evidence')
    op.drop_table('engagements')
    op.drop_table('audit_events')
    op.drop_table('organizations')
    op.drop_table('audit_firms')
    # ### end Alembic commands ###
